### ISSUE TITLE
Where are DllImports?

### ISSUE THREAD

**Issue by hypersonik** [ArgusMagnus/FFTW.NET#2]
I can't compile the source code because some functions are missing (fftw_init_threads, fftw_export_wisdom, etc).
There is no trace of DllImport declarations, so definitely the source must be incomplete.
Maybe I need some other resources?

**Comment by ArgusMagnus** [comment]
The DllImports are autogenerated from FftwInterop.tt, Visual Studio should generate the code when compiling.

**Comment by hypersonik** [comment]
I cannot manage to get them autogenerated.
I must learn more about T4, but that will be tomorrow.
Thanks for your answer.

**Comment by hypersonik** [comment]
I've found out that I've to install "Visual Studio extension development" workload in order to enable T4.
Source:
https://developercommunity.visualstudio.com/content/problem/29336/can-not-find-t4-in-visual-studio-2017.html

**Comment by ArgusMagnus** [comment]
Thanks for reporting back your solution.

But I wonder then why it worked for me, Im also using VS 17 and never had to install that extension..
