### ISSUE TITLE
Does not seem to import functions from the dll

### ISSUE THREAD

**Issue by Mathias-Fuchs** [ArgusMagnus/FFTW.NET#5]
Hello Argus ... think I placed the two fftw dll into the right locations ... still getting this: 
![capture3](https://user-images.githubusercontent.com/16633899/38951401-6b7f4cf6-4340-11e8-91b5-47f17027aae8.PNG)
any idea? how to go about finding the reason?

**Comment by ArgusMagnus** [comment]
These methods are generated by a T4 template, you need to run the custom tool on the *.tt file to generate the code.
________________________________

**Comment by Mathias-Fuchs** [comment]
ok, thanks!
